/**
 * Maps feed `all_cats` subcategory tags to one of the 16 top-level catalogue collections.
 * Tags that exactly match a parent collection name are resolved automatically.
 * Derived from feed tag ↔ Catalogue co-occurrence in active-products.csv.
 */
export const CATEGORY_TAG_TO_PARENT_COLLECTION: Readonly<Record<string, string>> = {
    Accessories: 'Sexy Lingerie',
    'Anal Beads': 'Anal Toys',
    'Anal Dildos': 'Dildos',
    'Anal Sundries': 'Anal Toys',
    'Anal Vibrators': 'Anal Toys',
    Aphrodisiacs: 'Enhancers',
    Aromas: 'Essentials',
    'Babydolls and Chemise': 'Sexy Lingerie',
    Bodystockings: 'Sexy Lingerie',
    'Bondage Hoods': 'Bondage',
    'Bras and Knickers': 'Sexy Lingerie',
    Bridal: 'Sexy Lingerie',
    'Bullets and Eggs': 'Vibrators',
    'Butt Plugs': 'Anal Toys',
    'Classic Vibrators': 'Vibrators',
    'Clit Teasers': 'Vibrators',
    'Cock Rings and Cages': 'Bondage',
    Condoms: 'Essentials',
    Costumes: 'Sexy Lingerie',
    'Creams and Sprays': 'Enhancers',
    'Dildos &amp; Dongs': 'Dildos',
    'Double Enders': 'Dildos',
    'Eat Me': 'Fun and Games',
    'Eggs &amp; Rings': 'Vibrators',
    Female: 'Sex Dolls',
    Fetish: 'Bondage',
    'Finger Fun': 'Toys For Her',
    'For Her': 'Essentials',
    'For Him': 'Toys For Him',
    'For Them': 'Essentials',
    'Fun Vibrators': 'Vibrators',
    'G Spot': 'Vibrators',
    Games: 'Couples',
    Gifts: 'Couples',
    'Glass Dildos': 'Dildos',
    'Hen and Stag': 'Fun and Games',
    Hosiery: 'Sexy Lingerie',
    'Lingerie Sets': 'Sexy Lingerie',
    Lubricants: 'Essentials',
    Male: 'Dildos',
    Massage: 'Couples',
    Masturbators: 'Toys For Him',
    "Men's Sexy Underwear": 'Sexy Lingerie',
    'Nipple Play': 'Toys For Her',
    'Penis Pumps': 'Toys For Him',
    Playtime: 'Couples',
    'Plus Size': 'Sexy Lingerie',
    'Prostate Massagers': 'Toys For Him',
    'Rabbit Vibrators': 'Vibrators',
    Realistic: 'Vibrators',
    'Realistic Vaginas': 'Toys For Him',
    'Remote Control': 'Vibrators',
    'Remote Vibrators': 'Vibrators',
    Restraints: 'Bondage',
    Romance: 'Couples',
    SALES: 'Couples',
    'Sexual Health': 'Sexual Health &amp; Wellbeing',
    'Sleeves &amp; Rings': 'Toys For Him',
    'Strap On Vibes': 'Vibrators',
    'Strap Ons': 'Dildos',
    'Suction Vibrators': 'Vibrators',
    Sundries: 'Essentials',
    'Teddies and Bodies': 'Sexy Lingerie',
    Underwear: 'Fun and Games',
    'Vibe Virgins': 'Vibrators',
    'Vibrator Kits': 'Vibrators',
    'Wand Vibrators': 'Vibrators',
    'Waterproof Vibrators': 'Vibrators',
    Whips: 'Bondage',
};
